### PR TITLE
Hangman: fix indentation, reword a few comments

### PR DESCRIPTION
**Pull request by Mystifi**
This indentation was literally killing me, sorry. Also, reworded a couple comments to fit the conditional checking. Hopefully I didn't break anything

### CODE REVIEW

**Comment by Asheviere** [comment]
Ugh blame VSC for the indentation. I'll look over this when I have the time.

**Comment by Mystifi** [comment]
Yeah, I couldn't check the code via `npm test` because of it. :/

**Comment by Mystifi** [comment]
Also, line breaks seem to be CRLF instead of LF, and ESLint's saying there are just about 3,400 errors. Is this because of VSC too?

**Comment by Asheviere** [comment]
I actually think my config's fucked.

**Pull request merged**
